### ISSUE TITLE
Asignar Dirección IP a Host

### ISSUE THREAD

**Issue by Librehugo** [IssabelFoundation/system#26]
Buena tarde Issabel,

Podrán generar el cambio al siguiente archivo: "dhcpconfig", esta ubicado en /usr/share/issabel/privileged/.
La línea que indica el detalles: 473
    foreach (file('/etc/dhcpd.conf') as $s) {
Por esta:
    foreach (file('/etc/dhcp/dhcpd.conf') as $s) {

Saludos.

**Comment by asternic** [comment]
Gracias, modificado en el commit c1a7ead
