### ISSUE TITLE
Web interface modify  

### ISSUE THREAD

**Issue by afzalmahi70** [IssabelFoundation/system#28]
Hello sir
I want modify Issabel PBX interface modify and remove FAX, Email and other service. Any one help how i find the source code from our server. When i  inspect from our browser i can show the source code but i can't modified it

**Comment by asternic** [comment]
You can use the issabel-menuremove utility to remove menues from the GUI so they won't show any more. Take into account that once you remove the menu, you won't be able to add it just as simple as removing it

 From your terminal run:

issabel-menuremove fax
issabel-menuremove virtual_fax
issabel-menuremove faxlist
issabel-menuremove faxnew
issabel-menuremove sendfax
issabel-menuremove faxqueue
issabel-menuremove faxmaster
issabel-menuremove faxclients
issabel-menuremove faxviewer
issabel-menuremove faxutils


issabel-menuremove email_template
issabel-menuremove email_admin
issabel-menuremove email_domains
issabel-menuremove email_accounts
issabel-menuremove email_relay
issabel-menuremove email_list
issabel-menuremove email_stats
issabel-menuremove webmail

Also, this place is for reporting software bugs. For support request please use the proper channels (issabel forum or telegram group).
